### ISSUE TITLE
What is the `metric_id` in `pmcs_get_current_metric_value`

### ISSUE THREAD

**Issue by Msiavashi** [jcsaezal/pmctrack#14]
I want to measure the LLC misses at kernel level. I see you mention to use `int pmcs_get_current_metric_value( struct task_struct* task, int metric_id, uint64_t* value )` function after setting `prof_enabled` to 1 in `tast_struct`. But I can't find valid values for `metric_id`.

**Comment by jcsaezal** [comment]
This is explained in Sec. 3.2.1 of this paper on PMCTrack: <https://artecs.dacya.ucm.es/files/cj-jcsaez-pmctrack-2017.pdf>

The function is invoked from a scheduler implemented within the Linux kernel. In invoking it, PMCTrack will call the `pmcs_get_current_metric_value()` operation of the monitoring module that is currently enabled. As stated in the aforementioned paper, *"each metric is assigned a numerical ID, which is known by the scheduler and the monitoring module"*. Therefore, the ID should be unique for a metric within a monitoring module, but it is up to the monitoring module developer to decide which ID to associate with the various metrics it exports to the scheduler. 

If you want to gather LLC Misses from the scheduler's code, then you have no other choice but to build your own monitoring module that actually gathers that event count for as many architectures as you need. Recall that the point of that API call, is to allow the creation of  an architecture-independent scheduler implementation.  The monitoring module (in the kernel module), is the one that deals with architecture specific stuff, perhaps by using conditional compilation.
