### ISSUE TITLE
Obtaining zeroes when capturing pmc

### ISSUE THREAD

**Issue by sirfonzie** [jcsaezal/pmctrack#5]
Hi,

I am using XU3 with PMCTrack. I followed your guide on getting PMCTrack on the XU3.
Mostly it works, except for a small error during patching where heap #1 was not successful.

However, everything else worked and compiled.
Early test seem to point that pmctrack works but when I start using larger benchmark applications (e.g. parboil) I start getting zeroes in my data. (see example below)

I have tried setting the mm_manager to 1, but i get an error and I found a post in odroid forum that advises to set it to 0.

I hope someone can advise me what I am doing wrong.
Or better still have a working image for XU3.
I would like to obtain performance counters and energy reading of an application for my research work and pmctrack+odroid-xu3 seem to be my best bet.

-----------------------------------------------------------------

odroid@odroid:~/PB/parboil$ pmctrack -T 1 -c instr,cycles,llc_misses ./parboil r       un cutcp base small
[Event-to-counter mappings]
pmc1=instr
pmc2=cycles
pmc3=llc_misses
[Event counts]
nsample    pid      event          pmc1          pmc2          pmc3
Parboil parallel benchmark suite, version 0.2

read 5943 atoms from file '/home/odroid/PB/parboil/datasets/cutcp/small/input/wa       tbox.sl40.pqr'
extent of domain is:
  minimum -19.998 -19.941 -19.961
  maximum 19.974 20 19.974
padding domain by 0.5 Angstroms
domain lengths are 40.972 by 40.941 by 40.935

      1   4158       tick      45426348      68833709         78206
      2   4158       tick             0             0             0
      3   4158       tick             0             0             0
      4   4158       tick             0             0             0
      5   4158       tick             0             0             0
      6   4158       tick             0             0             0
      7   4158       tick             0             0             0
      8   4158       tick             0             0             0
      9   4158       tick             0             0             0
     10   4158       tick             0             0             0
     11   4158       tick             0             0             0
     12   4158       tick             0             0             0
     13   4158       tick             0             0             0
     14   4158       tick             0             0             0
     15   4158       tick             0             0             0
     16   4158       tick             0             0             0
     17   4158       tick             0             0             0
     18   4158       tick             0             0             0
     19   4158       tick             0             0             0
     20   4158       tick             0             0             0
     21   4158       tick             0             0             0
     22   4158       tick             0             0             0
     23   4158       tick             0             0             0
     24   4158       tick             0             0             0
     25   4158       tick             0             0             0
     26   4158       tick             0             0             0
     27   4158       tick             0             0             0
     28   4158       tick             0             0             0
     29   4158       tick             0             0             0
     30   4158       tick             0             0             0
     31   4158       tick             0             0             0
     32   4158       tick             0             0             0
     33   4158       tick             0             0             0
IO        : 0.035814
Compute   : 32.895776
Timer Wall Time: 32.931599
Pass
     34   4158  migration        173104        654628          2465
     35   4158       exit       4209084      13617505         58913
odroid@odroid:~/PB/parboil$

**Comment by jcsaezal** [comment]
Hi,

Perhaps, this has to do with the cores' idle states. When a core of the big LITTLE processor enters an idle state, performance counters are disabled automatically on that core. The hardware itself takes care of that on ARM. It is not a PMCTrack thing. Nevertheless, we plan to add support in our tool so that the kernel module is notified by the core kernel when a CPU is about to enter/exit an idle state on ARM platforms. 

In the meantime, you could try to overcome this issue by disabling idle states just when your experiments are running. [Here](https://github.com/jcsaezal/pmctrack/files/1443956/cpuidle_odroid.txt) you can find a script (rename it to `cpuidle_odroid.sh`) that lets you disable idle states easily. 

```
Usage:
$ sudo ./cpuidle_odroid.sh [enable|disable]
```
 
Please let me know if that solves your problem. In addition. you could also try binding your application explicitly to a big or to a little core via the `-b <cpu_number>` option of `pmctrack`, and see if the core type makes a difference.

--Juan Carlos

**Comment by sirfonzie** [comment]
Hi,

Thank you very much for the response. Disabling the idle didnt work. I still got zeroes for most of the counts.
However, forcing the application to run on a particular core seems to work (see a snippet of the output below). I tried forcing the application to run a benchmark on one of the core using the following command (pmctrack -b 1 -S -T 0.1 -c instr,cycles,llc_misses ./parboil run cutcp base small).

Does the output below look correct?

     82      1       tick    1434267365    1385749454         52305
     83      2       tick          5751        152989           396
     84      3       tick         38688        187599           284
     85      4       tick             0             0             0
     86      5       tick             0             0             0
     87      6       tick             0             0             0
     88      7       tick             0             0             0
     89      0       tick             0             0             0
     90      1       tick    1433171355    1383979148         46355
     91      2       tick          5683        148644           390
     92      3       tick         38698        167420           220
     93      4       tick             0             0             0

**Comment by jcsaezal** [comment]
Hi,

Could you provide more information on the application you want to monitor? Is it single-threaded or multithreaded? Does it create child processes? Is it a shell script or a regular executable file what you are launching?

If it is a regular single-threaded application that does not create child processes you should not be using the -S switch (system-wide mode) when invoking PMCTrack. 

Thanks.

**Comment by sirfonzie** [comment]
Currently I am using the parboil benchmark, "cutcpu" application, "base" version with "small" input data.
The code was compiled on the odroid itself and if I am not mistalen it is single-threaded that does not fork/spawn processes.

Btw, why cant I use -S switch? Doesnt the -S switch allows me to see all the pmc on all the cores?

-Fauzi

**Comment by sirfonzie** [comment]
One more query. The -S switch will display the pmc count for each core and repeat this this the application ends. But I notice the count is not cumulative. So does the pmc count reset after being displayed? Example below:

    233      0       tick             0             0             0
    234      1       tick             0             0             0
    235      2       tick             0             0             0
    236      3       tick         44263         90189            41
    237      4       tick             0             0             0
    238      5       tick    2851724706    1985926096           708
    239      6       tick             0             0             0
    240      7       tick             0             0             0
    241      0       tick             0             0             0
    242      1       tick             0             0             0
    243      2       tick             0             0             0
    244      3       tick         40087         76663            23
    245      4       tick             0             0             0
    246      5       tick    2851214487    1985703383           569
    247      6       tick             0             0             0
    248      7       tick             0             0             0
    249      0       tick             0             0             0
    250      1       tick             0             0             0
    251      2       tick             0             0             0
    252      3       tick         44331         91008            59
    253      4       tick             0             0             0
    254      5       tick    2850863806    1985944672           400
    255      6       tick             0             0             0
    256      7       tick             0             0             0

**Comment by jcsaezal** [comment]
Hi,

Note that the `-S` switch displays system-wide information, this is, it shows performance counts for all applications running on the system (including OS services and daemons) but in a per-CPU fashion. Actually the zeroes that appear in the previous log you sent correspond to inactive CPUs, hence the zero count. Because you want to monitor the performance metrics of ONLY ONE application,  you should not use `-S`. 

Since the application does not create child processes  it should work without the `-S` switch. Have you tried that (but with binding enabled `-b <CPU>` and cpuidle disabled)? 

Please let me how if that works, and if it doesn't I will keep looking into it.

FInally note that, as stated in the [Getting Started page](https://pmctrack.dacya.ucm.es/getting-started/), the default behavior of the TBS mode (enabled with -T) is to display the counts gathered during the last sampling interval, so they are not cumulative counts. To get these cumulative counts at the end of the execution you could use the -A switch; you might as well process the output with a simple script to calculate the aggregate counts you want.  

--Juan Carlos

**Comment by sirfonzie** [comment]
Hi,

My apologies for not replying sooner, but I was trying a few thing and finally managed to solve the problem. It seems that when I use pmctrack, I should not pass a bash script (.sh) file to execute the program and use the program directly. 

For example:
# pmctrack -b 2 -T 0.1 -c instr ./pns 200 200 200

this gives me output:
pmc1=instr
[Event counts]
nsample    pid      event          pmc1
      1   4010       tick       9387877
      2   4010       tick      11794027
      3   4010       tick      11812182
      4   4010       tick      11817836
      5   4010       tick      11810485
...

BUT
# pmctrack -b 2 -T 0.1 -c instr ./das.sh
where "das.sh" contains  "./pns 200 200 200" 
this gives me output:

pmc1=instr
[Event counts]
nsample    pid      event          pmc1
      1   4005       tick        888943
      2   4005       tick             0
      3   4005       tick             0
      4   4005       tick             0
      5   4005       tick             0
...

Everything else works fine as long as I use the program directly.
Again, my apologies for troubling you for my mistake.

-Fauzi

**Comment by jcsaezal** [comment]
Hi,

Indeed, when you use a bash script to launch a program, PMCTrack monitors the Bash process, which in that case is waiting for your program to terminate, hence the zero counts. So, launching the program directly with PMCTrack or via `exec <command>` in the BASH script solves the problem.

I am glad it finally works!

--Juan Carlos
