### ISSUE TITLE
Error when setting up PMCTrack on XU3

### ISSUE THREAD

**Issue by sirfonzie** [jcsaezal/pmctrack#7]
Hi. When I was following the guide to patch the kernel in the xu3, I came across the following error.
The error states that the following patch was rejected.
Is this something I should be concerned about?

==============================================================

```
--- arch/arm/boot/dts/exynos5422_evt0.dtsi
+++ arch/arm/boot/dts/exynos5422_evt0.dtsi
@@ -91,6 +91,17 @@
                };
        };

+       arm-pmu {
+                       compatible = "arm,cortex-a15-pmu";
+                       interrupt-parent = <&combiner>;
+                       interrupts = <1 2>, <7 0>, <16 6>, <19 2>;
+       /*
+                       compatible = "arm,cortex-a7-pmu";
+                       interrupt-parent = <&gic>;
+                       interrupts = <0 192 4>, <0 193 4>, <0 194 4>, <0 195 4>;
+       */
+       };
+
        watchdog@10020000 {
                compatible = "samsung,s3c2410-wdt";
                reg = <0x101D0000 0x100>;
```
==============================================================

**Comment by jcsaezal** [comment]
Hi,

Sorry for the delay. 

Those lines in the dtsi file are important, as they enable the interrupts associated with counter overflow on the ARM Cortex A15 big cores. PMCTrack uses these interrupts for various things; some monitoring modes, such as EBS, will simply not work without them.
 
Which kernel version are you trying to apply the patch to? I believe the patch available for XU3/XU4 was tested on v3.10.96 (longterm version).

Regards,

Juan Carlos
