### ISSUE TITLE
Monitoring multiple application concurrently

### ISSUE THREAD

**Issue by sirfonzie** [jcsaezal/pmctrack#8]
Hi,

Would it be possible to concurrently obtain 5 applications pmc separately?
E.g. I have 5 applications that needs to run concurrently, but I need to obtain the pmc counts for each application.

**Comment by jcsaezal** [comment]
Hi,

Of course you can. All you have to do is launch as many separate instances of the `pmctrack` program as the number of applications you want to monitor (you can use the same or different hardware events configuration). Just make sure you do not turn on the system-wide monitoring mode (`-S` switch) when launching `pmctrack`. PMCTrack takes care of maintaining separate pmc counts for each application. 

I hope that helps.

Regards,

Juan Carlos
